// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHVwx2t_p8GXIXhR_1HpD3WFQ4l5DxuI',
    appId: '1:804094019299:web:5ad3da0e643c44c72527d6',
    messagingSenderId: '804094019299',
    projectId: 'fir-auth-lesson-bbc53',
    authDomain: 'fir-auth-lesson-bbc53.firebaseapp.com',
    storageBucket: 'fir-auth-lesson-bbc53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQipvpp69MJ43btZL3wSIeRzxGIC4M34',
    appId: '1:804094019299:android:0e2ccf86e4c8998f2527d6',
    messagingSenderId: '804094019299',
    projectId: 'fir-auth-lesson-bbc53',
    storageBucket: 'fir-auth-lesson-bbc53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOoSFLru_yZheSRi0LxuOg9tVGNl9d04U',
    appId: '1:804094019299:ios:06284a20c5e8f1742527d6',
    messagingSenderId: '804094019299',
    projectId: 'fir-auth-lesson-bbc53',
    storageBucket: 'fir-auth-lesson-bbc53.appspot.com',
    iosClientId:
        '804094019299-hajte7kfv6b3pmjmj3nbq1of49leq0rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson41AuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOoSFLru_yZheSRi0LxuOg9tVGNl9d04U',
    appId: '1:804094019299:ios:06284a20c5e8f1742527d6',
    messagingSenderId: '804094019299',
    projectId: 'fir-auth-lesson-bbc53',
    storageBucket: 'fir-auth-lesson-bbc53.appspot.com',
    iosClientId:
        '804094019299-hajte7kfv6b3pmjmj3nbq1of49leq0rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson41AuthFirebase',
  );
}
